import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig(() => ({
  define: { global: 'globalThis' },
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      manifest: false,
      includeAssets: [
        'manifest.webmanifest',
        'favicon.svg',
        'icons/icon-192x192.png',
        'icons/icon-512x512.png',
        'icons/icon-maskable-512x512.png',
        'sounds/bgm.mp3',
      ],
      workbox: {
        // Only the app shell is installed up front. Games and comics stay on demand.
        globPatterns: ['index.html', 'assets/**/*.{js,css}'],
        navigateFallback: 'index.html',
        navigateFallbackDenylist: [/^\/daxigua\//, /^\/save-hange\//, /^\/admin\//],
        cleanupOutdatedCaches: true,
        runtimeCaching: [
          {
            // Only stable, query-free comic image URLs generated by COSService.
            urlPattern: /^https:\/\/levihan-1325571558\.cos-website\.ap-nanjing\.myqcloud\.com\/lh-[^/?]+\/[^?]+\.webp$/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'levihan-comics',
              expiration: { maxEntries: 120, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            urlPattern: /\/daxigua\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'game-daxigua',
              expiration: { maxEntries: 150, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            urlPattern: /\/save-hange\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'game-hange',
              expiration: { maxEntries: 40, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
  resolve: { alias: { '@': path.resolve(__dirname, '.') } },
  server: {
    // HMR is disabled in AI Studio via DISABLE_HMR env var.
    // Do not modify—file watching is disabled to prevent flickering during agent edits.
    hmr: process.env.DISABLE_HMR !== 'true',
    // Disable file watching when DISABLE_HMR is true to save CPU during agent edits.
    watch: process.env.DISABLE_HMR === 'true' ? null : {},
  },
}));
