import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import { createHash, timingSafeEqual } from 'node:crypto';
import path from 'path';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { defineConfig, loadEnv, type Plugin } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

const localDoujinAuth = (expectedPassword?: string): Plugin => {
  const middleware = (request: IncomingMessage, response: ServerResponse, next: () => void) => {
    if (request.url !== '/api/doujin-auth') {
      next();
      return;
    }

    response.setHeader('Content-Type', 'application/json; charset=utf-8');
    response.setHeader('Cache-Control', 'no-store');

    if (request.method !== 'POST') {
      response.statusCode = 405;
      response.setHeader('Allow', 'POST');
      response.end(JSON.stringify({ ok: false }));
      return;
    }

    let body = '';
    request.on('data', (chunk) => {
      body += chunk;
    });
    request.on('end', () => {
      if (!expectedPassword) {
        response.statusCode = 503;
        response.end(JSON.stringify({ ok: false }));
        return;
      }

      let suppliedPassword = '';
      try {
        const parsed = JSON.parse(body) as { password?: unknown };
        suppliedPassword = typeof parsed.password === 'string' ? parsed.password : '';
      } catch {
        // Invalid input is treated as a failed password attempt.
      }

      const suppliedHash = createHash('sha256').update(suppliedPassword).digest();
      const expectedHash = createHash('sha256').update(expectedPassword).digest();
      const isValid = timingSafeEqual(suppliedHash, expectedHash);
      response.statusCode = isValid ? 200 : 401;
      response.end(JSON.stringify({ ok: isValid }));
    });
  };

  return {
    name: 'local-doujin-auth',
    configureServer(server) {
      server.middlewares.use(middleware);
    },
    configurePreviewServer(server) {
      server.middlewares.use(middleware);
    },
  };
};

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');

  return ({
  define: { global: 'globalThis' },
  plugins: [
    localDoujinAuth(env.DOUJIN_PASSWORD),
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      manifest: false,
      includeAssets: [
        'manifest.webmanifest',
        'favicon.svg',
        'icons/icon-192x192.png',
        'icons/icon-512x512.png',
        'icons/icon-maskable-512x512.png',
        'images/archive-maintenance.png',
        'sounds/bgm.mp3',
      ],
      workbox: {
        // Only the app shell is installed up front. Games and comics stay on demand.
        globPatterns: ['index.html', 'assets/**/*.{js,css}'],
        navigateFallback: 'index.html',
        navigateFallbackDenylist: [/^\/daxigua\//, /^\/save-hange\//, /^\/admin\//],
        cleanupOutdatedCaches: true,
        runtimeCaching: [
          {
            // Only stable, query-free comic image URLs generated by COSService.
            urlPattern: /^https:\/\/levihan-1325571558\.cos-website\.ap-nanjing\.myqcloud\.com\/lh-[^/?]+\/[^?]+\.webp$/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'levihan-comics',
              expiration: { maxEntries: 120, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            urlPattern: /\/daxigua\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'game-daxigua',
              expiration: { maxEntries: 150, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            urlPattern: /\/save-hange\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'game-hange',
              expiration: { maxEntries: 40, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
  resolve: { alias: { '@': path.resolve(__dirname, '.') } },
  server: {
    // HMR is disabled in AI Studio via DISABLE_HMR env var.
    // Do not modify—file watching is disabled to prevent flickering during agent edits.
    hmr: process.env.DISABLE_HMR !== 'true',
    // Disable file watching when DISABLE_HMR is true to save CPU during agent edits.
    watch: process.env.DISABLE_HMR === 'true' ? null : {},
  },
  });
});
