import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import { createHash, timingSafeEqual } from 'node:crypto';
import path from 'path';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { defineConfig, loadEnv, type Plugin } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

const localDoujinAuth = (expectedPassword?: string): Plugin => {
  const middleware = (request: IncomingMessage, response: ServerResponse, next: () => void) => {
    if (request.url !== '/api/doujin-auth') {
      next();
      return;
    }

    response.setHeader('Content-Type', 'application/json; charset=utf-8');
    response.setHeader('Cache-Control', 'no-store');

    if (request.method !== 'POST') {
      response.statusCode = 405;
      response.setHeader('Allow', 'POST');
      response.end(JSON.stringify({ ok: false }));
      return;
    }

    let body = '';
    request.on('data', (chunk) => {
      body += chunk;
    });
    request.on('end', () => {
      if (!expectedPassword) {
        response.statusCode = 503;
        response.end(JSON.stringify({ ok: false }));
        return;
      }

      let suppliedPassword = '';
      try {
        const parsed = JSON.parse(body) as { password?: unknown };
        suppliedPassword = typeof parsed.password === 'string' ? parsed.password : '';
      } catch {
        // Invalid input is treated as a failed password attempt.
      }

      const suppliedHash = createHash('sha256').update(suppliedPassword).digest();
      const expectedHash = createHash('sha256').update(expectedPassword).digest();
      const isValid = timingSafeEqual(suppliedHash, expectedHash);
      response.statusCode = isValid ? 200 : 401;
      response.end(JSON.stringify({ ok: isValid }));
    });
  };

  return {
    name: 'local-doujin-auth',
    configureServer(server) {
      server.middlewares.use(middleware);
    },
    configurePreviewServer(server) {
      server.middlewares.use(middleware);
    },
  };
};

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');

  return ({
  define: { global: 'globalThis' },
  plugins: [
    localDoujinAuth(env.DOUJIN_PASSWORD),
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      manifest: false,
      includeAssets: [
        'manifest.webmanifest',
        'favicon.svg',
        'icons/icon-192x192.png',
        'icons/icon-512x512.png',
        'icons/icon-maskable-512x512.png',
        'images/archive-maintenance.webp',
        'sounds/bgm.mp3',
      ],
      workbox: {
        // Only the app shell is installed up front. Games and comics stay on demand.
        globPatterns: ['index.html', 'assets/**/*.{js,css}'],
        // 加密阅读器（pdfjs-dist + crypto-js，约 414 KB）只服务「含有敏感元素」的本子，
        // 且它本身就必须联网取密文，离线预缓存没有意义 —— 别让每个访客都在后台拖它。
        globIgnores: ['assets/SecureComicReader-*.js'],
        navigateFallback: 'index.html',
        // ⚠️ /admin 必须连**不带斜杠**的写法一起排除：
        // 只写 /^\/admin\// 时，访问 /admin（无斜杠）会被 SW 回退成前台首页，
        // 用户看到的是「主页」而不是后台（2026-09-21 实测踩过）。
        navigateFallbackDenylist: [/^\/daxigua\//, /^\/save-hange\//, /^\/admin(\/|$)/],
        cleanupOutdatedCaches: true,
        runtimeCaching: [
          {
            // Only stable, query-free comic image URLs generated by COSService.
            urlPattern: /^https:\/\/levihan-1325571558\.cos-website\.ap-nanjing\.myqcloud\.com\/lh-[^/?]+\/[^?]+\.webp$/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'levihan-comics',
              expiration: { maxEntries: 120, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            urlPattern: /\/daxigua\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'game-daxigua',
              expiration: { maxEntries: 150, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            urlPattern: /\/save-hange\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'game-hange',
              expiration: { maxEntries: 40, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
  resolve: { alias: { '@': path.resolve(__dirname, '.') } },
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          // React 核心库
          'react-vendor': ['react', 'react-dom'],
          // PDF.js 相关（大文件，单独分割）
          'pdfjs-vendor': ['pdfjs-dist'],
          // CloudBase SDK
          'cloudbase-vendor': ['@cloudbase/js-sdk'],
          // 加密库
          'crypto-vendor': ['crypto-js'],
          // AWS SDK
          'aws-vendor': ['@aws-sdk/client-s3'],
          // 其他第三方库
          'vendor': ['lucide-react', 'qrcode', 'html-to-image', 'react-pinch-zoom-pan'],
        },
      },
    },
    chunkSizeWarningLimit: 1000, // 提高警告阈值到 1MB
  },
  server: {
    // HMR is disabled in AI Studio via DISABLE_HMR env var.
    // Do not modify—file watching is disabled to prevent flickering during agent edits.
    hmr: process.env.DISABLE_HMR !== 'true',
    // Disable file watching when DISABLE_HMR is true to save CPU during agent edits.
    watch: process.env.DISABLE_HMR === 'true' ? null : {},
    // 云函数（admin-upload / registerWithPassword / loginWithPassword）的 CORS 白名单
    // 只认 levihan.asia / www / admin / localhost:5173 / localhost:4173，
    // 而本地 dev 跑在 localhost:3000（--host=0.0.0.0 时还有局域网 IP），跨域会被浏览器拦掉，
    // 表现为「后台有公告、前台空白」且登录注册一并失效。
    // 开发态改由 dev server 服务端转发（转发无 Origin，不受白名单影响）。
    // 前端地址收敛在 src/utils/cloudbaseEndpoint.ts，两处前缀必须一致。
    proxy: {
      '/__cf': {
        target: 'https://levihan-tudou-d0g7jivue1ccc4a35.service.tcloudbase.com',
        changeOrigin: true,
        secure: true,
        rewrite: (path) => path.replace(/^\/__cf/, ''),
      },
    },
  },
  });
});
