'use strict';
const crypto = require('crypto');
const { ApiError } = require('../../errors');
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function admin(ctx) { if (!ctx.actorId || !UUID.test(ctx.actorSessionId || '')) throw new ApiError(401, 'SESSION_EXPIRED', 'Session expired'); if (ctx.actorRole !== 'admin') throw new ApiError(403, 'ACCESS_DENIED', 'Administrator access required'); }
function exact(body, required, optional = []) { return body && Object.getPrototypeOf(body) === Object.prototype && required.every((key) => Object.hasOwn(body, key)) && Object.keys(body).every((key) => required.includes(key) || optional.includes(key)); }
function version(value) { if (!Number.isSafeInteger(value) || value < 1) throw new ApiError(400, 'VALIDATION_FAILED', 'Version is invalid'); return value; }
function id(value) { if (!UUID.test(value || '')) throw new ApiError(400, 'VALIDATION_FAILED', 'ID is invalid'); return value; }
function text(value, max, empty = false) { if (typeof value !== 'string') throw new ApiError(400, 'VALIDATION_FAILED', 'Text is invalid'); const normalized = value.trim(); if ((!empty && !normalized) || normalized.length > max) throw new ApiError(400, 'VALIDATION_FAILED', 'Text is invalid'); return normalized; }
function list(ctx, allowedStatus) { const limit = ctx.query.limit === undefined ? 20 : Number(ctx.query.limit); if (!Number.isSafeInteger(limit) || limit < 1 || limit > 100) throw new ApiError(400, 'VALIDATION_FAILED', 'Limit is invalid'); const status = ctx.query.status || null; if (status && allowedStatus && !allowedStatus.has(status)) throw new ApiError(400, 'VALIDATION_FAILED', 'Status is invalid'); let beforeAt = null; let beforeId = null; if (ctx.query.cursor) { const split = String(ctx.query.cursor).split('|'); if (split.length !== 2 || Number.isNaN(Date.parse(split[0])) || !UUID.test(split[1])) throw new ApiError(400, 'VALIDATION_FAILED', 'Cursor is invalid'); [beforeAt, beforeId] = split; } return { limit, status, beforeAt, beforeId }; }
function operation(ctx) { if (typeof ctx.idempotencyKey !== 'string' || !ctx.idempotencyKey || !/^[a-f0-9]{64}$/i.test(ctx.idempotencyRequestHash || '')) throw new ApiError(400, 'IDEMPOTENCY_REQUIRED', 'Idempotency key is required'); }
function answerHashes(values, rule, hash) { if (!Array.isArray(values) || values.length < 1 || values.length > 8) throw new ApiError(400, 'VALIDATION_FAILED', 'Answers are invalid'); return values.map((value) => { let normalized = text(value, 256); if (rule.includes('lowercase')) normalized = normalized.toLocaleLowerCase('zh-CN'); if (rule.includes('collapse_whitespace')) normalized = normalized.replace(/\s+/gu, ' '); return hash(normalized); }); }
function createAdminConsoleService({ repository, answerHasher = (value) => crypto.createHash('sha256').update(value).digest('hex') } = {}) {
  if (!repository) throw new Error('Admin console repository is required');
  const read = (method, statuses) => async (ctx) => { admin(ctx); return repository[method]({ adminId: ctx.actorId, adminSessionId: ctx.actorSessionId, ...list(ctx, statuses), search: ctx.query.search ? text(ctx.query.search, 64) : null, action: ctx.query.action ? text(ctx.query.action, 100) : null }); };
  return {
    async dashboard(ctx) { admin(ctx); return repository.dashboard({ adminId: ctx.actorId, adminSessionId: ctx.actorSessionId }); },
    listComments: read('listComments', new Set(['pending', 'published', 'hidden', 'deleted', 'rejected'])),
    listReports: read('listReports', new Set(['pending', 'reviewing', 'resolved', 'rejected'])),
    listUsers: read('listUsers', new Set(['active', 'suspended', 'deleted'])),
    listQuestions: read('listQuestions', new Set(['draft', 'active', 'disabled'])),
    listJobs: read('listJobs', null), listAudit: read('listAudit', null),
    async setUserStatus(ctx) { admin(ctx); operation(ctx); if (!exact(ctx.body, ['version', 'status', 'reason']) || !['active', 'suspended'].includes(ctx.body.status)) throw new ApiError(400, 'VALIDATION_FAILED', 'User status input is invalid'); return { user: await repository.setUserStatus({ adminId: ctx.actorId, adminSessionId: ctx.actorSessionId, targetId: id(ctx.params.id), expectedVersion: version(ctx.body.version), status: ctx.body.status, reason: text(ctx.body.reason, 500), idempotencyKey: ctx.idempotencyKey, requestHash: ctx.idempotencyRequestHash, requestId: ctx.requestId }) }; },
    async createQuestion(ctx) { admin(ctx); operation(ctx); if (!exact(ctx.body, ['prompt', 'options', 'acceptedAnswers', 'normalizationRule', 'samplingWeight'])) throw new ApiError(400, 'VALIDATION_FAILED', 'Question input is invalid'); const rule = ctx.body.normalizationRule; if (!['trim', 'trim_lowercase', 'trim_lowercase_collapse_whitespace'].includes(rule) || !Array.isArray(ctx.body.options) || ctx.body.options.length < 2 || ctx.body.options.length > 8 || !Number.isSafeInteger(ctx.body.samplingWeight) || ctx.body.samplingWeight < 1 || ctx.body.samplingWeight > 1000) throw new ApiError(400, 'VALIDATION_FAILED', 'Question input is invalid'); const options = ctx.body.options.map((x) => text(x, 256)); if (new Set(options).size !== options.length) throw new ApiError(400, 'VALIDATION_FAILED', 'Question options are invalid'); return { question: await repository.createQuestion({ adminId: ctx.actorId, adminSessionId: ctx.actorSessionId, prompt: text(ctx.body.prompt, 1000), options, acceptedAnswerHashes: answerHashes(ctx.body.acceptedAnswers, rule, answerHasher), normalizationRule: rule, samplingWeight: ctx.body.samplingWeight, idempotencyKey: ctx.idempotencyKey, requestHash: ctx.idempotencyRequestHash, requestId: ctx.requestId }) }; },
    async updateQuestion(ctx) { admin(ctx); operation(ctx); if (!exact(ctx.body, ['version'], ['prompt', 'options', 'acceptedAnswers', 'normalizationRule', 'samplingWeight'])) throw new ApiError(400, 'VALIDATION_FAILED', 'Question input is invalid'); const changes = {}; if (ctx.body.prompt !== undefined) changes.prompt = text(ctx.body.prompt, 1000); if (ctx.body.options !== undefined) { if (!Array.isArray(ctx.body.options) || ctx.body.options.length < 2 || ctx.body.options.length > 8) throw new ApiError(400, 'VALIDATION_FAILED', 'Question options are invalid'); changes.options = ctx.body.options.map((item) => text(item, 256)); if (new Set(changes.options).size !== changes.options.length) throw new ApiError(400, 'VALIDATION_FAILED', 'Question options are invalid'); } if (ctx.body.samplingWeight !== undefined) { if (!Number.isSafeInteger(ctx.body.samplingWeight) || ctx.body.samplingWeight < 1 || ctx.body.samplingWeight > 1000) throw new ApiError(400, 'VALIDATION_FAILED', 'Sampling weight is invalid'); changes.samplingWeight = ctx.body.samplingWeight; } if (ctx.body.acceptedAnswers !== undefined) { if (!['trim', 'trim_lowercase', 'trim_lowercase_collapse_whitespace'].includes(ctx.body.normalizationRule)) throw new ApiError(400, 'VALIDATION_FAILED', 'Normalization rule is required when answers change'); changes.normalizationRule = ctx.body.normalizationRule; changes.acceptedAnswerHashes = answerHashes(ctx.body.acceptedAnswers, ctx.body.normalizationRule, answerHasher); } if (!Object.keys(changes).length) throw new ApiError(400, 'VALIDATION_FAILED', 'No question changes supplied'); return { question: await repository.updateQuestion({ adminId: ctx.actorId, adminSessionId: ctx.actorSessionId, questionId: id(ctx.params.id), expectedVersion: version(ctx.body.version), changes, idempotencyKey: ctx.idempotencyKey, requestHash: ctx.idempotencyRequestHash, requestId: ctx.requestId }) }; },
    async setQuestionStatus(ctx) { admin(ctx); operation(ctx); if (!exact(ctx.body, ['version', 'status']) || !['active', 'disabled'].includes(ctx.body.status)) throw new ApiError(400, 'VALIDATION_FAILED', 'Question status input is invalid'); return { question: await repository.setQuestionStatus({ adminId: ctx.actorId, adminSessionId: ctx.actorSessionId, questionId: id(ctx.params.id), expectedVersion: version(ctx.body.version), status: ctx.body.status, idempotencyKey: ctx.idempotencyKey, requestHash: ctx.idempotencyRequestHash, requestId: ctx.requestId }) }; },
    async retryJob(ctx) { admin(ctx); operation(ctx); if (!exact(ctx.body, ['version'])) throw new ApiError(400, 'VALIDATION_FAILED', 'Retry input is invalid'); return { job: await repository.retryJob({ adminId: ctx.actorId, adminSessionId: ctx.actorSessionId, jobId: id(ctx.params.id), expectedVersion: version(ctx.body.version), idempotencyKey: ctx.idempotencyKey, requestHash: ctx.idempotencyRequestHash, requestId: ctx.requestId }) }; },
  };
}
module.exports = { createAdminConsoleService };
