#!/usr/bin/env python3
"""Build the shared UI sprite atlas from the named source artwork.

Add future UI images to SOURCES below, then run `npm run sprites`.
The walking strip is split into its three animation frames automatically.
"""

from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "assets/ui-sprite-sources"
OUTPUT = ROOT / "public/images/ui-sprite.webp"
GENERATED_TS = ROOT / "src/components/uiSprite.generated.ts"
ATLAS_WIDTH = 1024
PADDING = 4

SOURCES = {
    "resources": "资源外链.png",
    "doujin": "土豆粮仓.png",
    "dispatch": "联络.png",
    "home": "兵团驻地.png",
    "game-watermelon": "合成大西皮.png",
    "restaurant": "巨树餐厅.png",
    "tatakaru": "塔塔开.png",
    "nav-companion": "底部行走小人2.png",
    "game-hange": "拯救韩吉.png",
    "game-lihan": "利了个韩.png",
    "back-to-top": "向上按钮.png",
    "volume": "音量按钮.png",
    "button-wide": "button.宽png.png",
    "button-narrow": "button.（窄）png.png",
    "levi-peek": "利威尔趴趴.png",
    "hange-peek": "韩吉趴趴.png",
}


def load_sprites():
    sprites = [(name, Image.open(SOURCE_DIR / filename).convert("RGBA")) for name, filename in SOURCES.items()]
    walking = Image.open(SOURCE_DIR / "底部行走小人.png").convert("RGBA")
    # Transparent gaps in the supplied strip separate these three poses.
    for index, bounds in enumerate(((0, 0, 92, 170), (114, 0, 209, 170), (243, 0, 335, 170)), 1):
        sprites.append((f"walk-{index}", walking.crop(bounds)))
    return sprites


def pack(sprites):
    placed = {}
    x = y = row_height = PADDING
    for name, image in sorted(sprites, key=lambda item: item[1].height, reverse=True):
        width, height = image.size
        if x + width + PADDING > ATLAS_WIDTH:
            x = PADDING
            y += row_height + PADDING
            row_height = 0
        placed[name] = (x, y, image)
        x += width + PADDING
        row_height = max(row_height, height)
    return placed, y + row_height + PADDING


def main():
    placed, atlas_height = pack(load_sprites())
    atlas = Image.new("RGBA", (ATLAS_WIDTH, atlas_height), (0, 0, 0, 0))
    entries = []
    for name, (x, y, image) in placed.items():
        atlas.alpha_composite(image, (x, y))
        entries.append(f"  '{name}': {{ x: {x}, y: {y}, width: {image.width}, height: {image.height} }},")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    atlas.save(OUTPUT, "WEBP", lossless=True, method=6)
    GENERATED_TS.write_text(
        "// Generated by scripts/generate-ui-sprite.py. Do not edit by hand.\n"
        f"export const UI_SPRITE_SIZE = {{ width: {ATLAS_WIDTH}, height: {atlas_height} }} as const;\n"
        "export const UI_SPRITES = {\n" + "\n".join(entries) + "\n} as const;\n"
        "export type UiSpriteName = keyof typeof UI_SPRITES;\n",
        encoding="utf-8",
    )
    print(f"Generated {OUTPUT.relative_to(ROOT)} ({ATLAS_WIDTH}x{atlas_height}) with {len(placed)} sprites")


if __name__ == "__main__":
    main()
