export type AdminList<T> = { items: T[]; nextCursor: string | null };
export type AdminUser = { id: string; username: string; role: 'member' | 'admin'; status: 'active' | 'suspended' | 'deleted'; version: number; createdAt: string; lastLoginAt: string | null; activeSessions: number };
export type Dashboard = { counts: { works: number; pendingSubmissions: number; pendingComments: number; pendingReports: number; activeUsers: number; failedUploads: number; failedJobs: number }; todos: Array<{ kind: string; count: number }>; system: { databaseVersion: string; snapshotVersion: number | null; storageHealth: 'healthy' | 'degraded' | 'unknown' }; recentAdminActions: Array<{ action: string; actorId: string | null; createdAt: string }> };
export type AdminQuestion = { id: string; prompt: string; options: string[]; normalizationRule: 'trim' | 'trim_lowercase' | 'trim_lowercase_collapse_whitespace'; status: 'draft' | 'active' | 'disabled'; version: number; samplingWeight: number; createdAt: string; updatedAt: string };
export type AdminJob = { id: string; kind: string; status: string; attempts: number; version: number; updatedAt: string; error: string | null };
export type AuditItem = { id: string; actorId: string | null; action: string; targetType: string; targetId: string | null; summary: Record<string, unknown>; createdAt: string };
export type ModerationItem = { id: string; status: string; body?: string; reason?: string; targetType?: string; targetId?: string; version: number; createdAt: string };
export type AdminSetting = { key: 'announcement' | 'adult_content_policy' | 'feature_flags'; value: Record<string, unknown>; version: number; updatedAt: string };
export type AdminHealth = { database: { ok: boolean; databaseVersion: string; snapshot: Record<string, unknown>; migration: Record<string, unknown>; jobs: Record<string, unknown> }; storage: { ok: boolean; region: string; publicBucketConfigured: boolean; privateBucketConfigured: boolean; publicCorsConfigured: boolean; privateCorsConfigured: boolean } };
export class AdminApiError extends Error { constructor(public readonly errorCode: string, message: string, public readonly status: number, public readonly requestId?: string) { super(message); this.name = 'AdminApiError'; } }
const API_ROOT = '/api/v1';
function cookie(name: string) { if (typeof document === 'undefined') return ''; const prefix = `${name}=`; const part = document.cookie.split(';').map((v) => v.trim()).find((v) => v.startsWith(prefix)); return part ? decodeURIComponent(part.slice(prefix.length)) : ''; }
async function parse(response: Response) { const payload: unknown = await response.json().catch(() => null); if (!response.ok) { const record = payload && typeof payload === 'object' ? payload as Record<string, unknown> : {}; if (response.status === 401 && typeof window !== 'undefined') window.dispatchEvent(new Event('admin-session-expired')); throw new AdminApiError(typeof record.errorCode === 'string' ? record.errorCode : 'INTERNAL_ERROR', typeof record.message === 'string' ? record.message : '操作失败', response.status, typeof record.requestId === 'string' ? record.requestId : undefined); } return payload; }
export async function adminRequest<T>(path: string): Promise<T> { return parse(await fetch(`${API_ROOT}${path}`, { credentials: 'include', headers: { accept: 'application/json' } })) as Promise<T>; }
export async function adminWrite<T = unknown>(path: string, body: unknown, idempotencyKey: string, method: 'POST' | 'PATCH' = 'POST'): Promise<T> { const csrf = cookie(import.meta.env.VITE_CSRF_COOKIE_NAME || 'lv_csrf'); if (!csrf) throw new AdminApiError('ACCESS_DENIED', 'CSRF token is unavailable', 403); const headers = new Headers({ accept: 'application/json', 'content-type': 'application/json', 'x-csrf-token': csrf, 'idempotency-key': idempotencyKey }); return parse(await fetch(`${API_ROOT}${path}`, { method, credentials: 'include', headers, body: JSON.stringify(body) })) as Promise<T>; }
function query(input: Record<string, string | number | null | undefined>) { const params = new URLSearchParams(); for (const [key, value] of Object.entries(input)) if (value !== null && value !== undefined && value !== '') params.set(key, String(value)); return params.size ? `?${params}` : ''; }
export const operationKey = () => typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `admin-${Date.now()}-${Math.random().toString(16).slice(2)}`;
export const getDashboard = () => adminRequest<Dashboard>('/admin/dashboard');
export const listUsers = (input: { status?: string; search?: string; cursor?: string; limit?: number } = {}) => adminRequest<AdminList<AdminUser>>(`/admin/users${query(input)}`);
export const setUserStatus = (id: string, version: number, status: 'active' | 'suspended', reason: string, key = operationKey()) => adminWrite<{ user: AdminUser }>(`/admin/users/${encodeURIComponent(id)}/status`, { version, status, reason }, key);
export const promoteUser = (id: string, version: number, password: string, key = operationKey()) => adminWrite<{ user: AdminUser }>(`/admin/users/${encodeURIComponent(id)}/promote`, { version, password }, key);
export const getSettings = () => adminRequest<{ items: AdminSetting[] }>('/admin/settings');
export const updateSetting = (setting: AdminSetting, value: Record<string, unknown>, key = operationKey()) => adminWrite<{ setting: AdminSetting }>(`/admin/settings/${encodeURIComponent(setting.key)}`, { version: setting.version, value }, key, 'PATCH');
export const getHealth = () => adminRequest<AdminHealth>('/admin/health');
export const listQuestions = (input: { status?: string; cursor?: string; limit?: number } = {}) => adminRequest<AdminList<AdminQuestion>>(`/admin/questions${query(input)}`);
export const createQuestion = (input: { prompt: string; options: string[]; acceptedAnswers: string[]; normalizationRule: string; samplingWeight: number }, key = operationKey()) => adminWrite<{ question: AdminQuestion }>('/admin/questions', input, key);
export const updateQuestion = (id: string, input: { version: number; prompt?: string; options?: string[]; acceptedAnswers?: string[]; normalizationRule?: 'trim' | 'trim_lowercase' | 'trim_lowercase_collapse_whitespace'; samplingWeight?: number }, key = operationKey()) => adminWrite<{ question: AdminQuestion }>(`/admin/questions/${encodeURIComponent(id)}`, input, key, 'PATCH');
export const setQuestionStatus = (id: string, version: number, status: 'active' | 'disabled', key = operationKey()) => adminWrite<{ question: AdminQuestion }>(`/admin/questions/${encodeURIComponent(id)}/status`, { version, status }, key);
export const listJobs = (input: { status?: string; cursor?: string; limit?: number } = {}) => adminRequest<AdminList<AdminJob>>(`/admin/jobs${query(input)}`);
export const retryJob = (id: string, version: number, key = operationKey()) => adminWrite<{ job: AdminJob }>(`/admin/jobs/${encodeURIComponent(id)}/retry`, { version }, key);
export const listAudit = (input: { action?: string; cursor?: string; limit?: number } = {}) => adminRequest<AdminList<AuditItem>>(`/admin/audit${query(input)}`);
export const listModeration = (kind: 'comments' | 'reports', input: { status?: string; cursor?: string; limit?: number } = {}) => adminRequest<AdminList<ModerationItem>>(`/admin/moderation/${kind}${query(input)}`);
