import React, { useState } from 'react';
import { AuthApiError, beginLegacyMigration, confirmRecoveryCode, installLegacyMigration, prepareLegacyMigration, recover } from './api';

export function LegacyMigrationPage({ onClose }: { onClose: () => void }) {
  const [credential, setCredential] = useState(''); const [password, setPassword] = useState('');
  const [recoveryCode, setRecoveryCode] = useState(''); const [prepareNonce, setPrepareNonce] = useState('');
  const [saved, setSaved] = useState(false); const [busy, setBusy] = useState(false); const [uncertain, setUncertain] = useState(false); const [message, setMessage] = useState('');
  const prepare = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); try { await beginLegacyMigration(credential.trim()); const result = await prepareLegacyMigration(); setRecoveryCode(result.recoveryCode); setPrepareNonce(result.prepareNonce); setCredential(''); } catch (error) { setMessage(error instanceof Error ? error.message : '迁移凭据无效'); } finally { setBusy(false); } };
  const install = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); try { await installLegacyMigration({ newPassword: password, recoveryCode, prepareNonce }); const confirmed = await confirmRecoveryCode(recoveryCode); window.dispatchEvent(new Event('levihan-auth-changed')); setPassword(''); setPrepareNonce(''); setRecoveryCode(''); setMessage(`账号 ${confirmed.user.username} 已迁移`); } catch (error) { if (error instanceof AuthApiError) { setUncertain(false); setMessage(error.message); } else { setUncertain(true); setMessage('安装结果可能已提交。请使用已保存的恢复码完成恢复，避免重复使用迁移凭据。'); } } finally { setBusy(false); } };
  const recoverUnknown = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { const result = await recover({ recoveryCode, newPassword: password }); setRecoveryCode(result.recoveryCode); setUncertain(false); setSaved(false); setMessage('恢复成功。请重新保存页面显示的新恢复码，再登录。'); } catch (error) { setMessage(error instanceof Error ? error.message : '恢复失败'); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-[#f5ecd7] p-5 text-[#2c241d]"><section className="mx-auto max-w-lg border-2 border-[#1c1611] bg-[#fffaf0] p-5 shadow-[6px_6px_0_#1c1611]"><h1 className="text-xl font-bold">迁移旧账号</h1><p className="my-3 text-sm">该入口只在迁移窗口开放。恢复码不会写入 localStorage 或 sessionStorage；离开页面前必须安全保存。</p>
    {!recoveryCode ? <form onSubmit={prepare} className="space-y-3"><label className="block">一次性迁移凭据<input aria-label="一次性迁移凭据" value={credential} onChange={(event) => setCredential(event.target.value)} minLength={43} required className="mt-1 w-full border p-2" /></label><button disabled={busy} className="border bg-[#1e4334] p-2 text-white">验证并生成恢复码</button></form> : <form onSubmit={uncertain ? recoverUnknown : install} className="space-y-3"><p>请先保存恢复码：</p><code className="block select-all border p-3 text-center">{recoveryCode}</code><label className="flex gap-2"><input aria-label="我已安全保存迁移恢复码" type="checkbox" checked={saved} onChange={(event) => setSaved(event.target.checked)} />我已安全保存恢复码</label><label className="block">新密码<input aria-label="迁移账号新密码" type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={12} required className="mt-1 w-full border p-2" /></label><button disabled={busy || !saved} className="border bg-[#1e4334] p-2 text-white">{uncertain ? '使用恢复码安全恢复' : '安装密码并完成迁移'}</button></form>}
    {message && <p role="status" className="mt-3 text-sm">{message}</p>}<button type="button" onClick={onClose} className="mt-5 underline">返回首页</button></section></main>;
}
