import React, { useEffect, useState } from 'react';
import { getMe } from '../features/auth/api';
import { getDashboard, type Dashboard } from './api';
import { AuditAdmin, JobsAdmin, ModerationAdmin, QuestionsAdmin, SubmissionsAdmin, UsersAdmin, WorksAdmin } from './modules';
export type AdminRoute = 'dashboard' | 'works' | 'submissions' | 'moderation' | 'users' | 'questions' | 'jobs' | 'audit';
const nav: Array<[AdminRoute, string]> = [['dashboard','仪表盘'],['works','作品'],['submissions','投稿'],['moderation','评论与举报'],['users','用户'],['questions','题库'],['jobs','快照与清理'],['audit','审计']];
const routes = nav.map(([route]) => route);
export function adminRouteFromHash(hash: string): AdminRoute { const route = hash.replace(/^#\/?/, '').split('/')[0] as AdminRoute; return routes.includes(route) ? route : 'dashboard'; }
const views: Partial<Record<AdminRoute,React.ComponentType>>={works:WorksAdmin,submissions:SubmissionsAdmin,moderation:ModerationAdmin,users:UsersAdmin,questions:QuestionsAdmin,jobs:JobsAdmin,audit:AuditAdmin};
export function AdminApp() { const [auth,setAuth]=useState<'loading'|'anonymous'|'denied'|'admin'>('loading'); const [route,setRoute]=useState<AdminRoute>(()=>adminRouteFromHash(window.location.hash)); const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [summary,setSummary]=useState(''); useEffect(()=>{ void getMe().then((me)=>setAuth(me.role==='admin'?'admin':'denied')).catch(()=>setAuth('anonymous')); },[]); useEffect(()=>{ const listener=()=>setRoute(adminRouteFromHash(window.location.hash)); const expired=()=>setAuth('anonymous'); window.addEventListener('hashchange',listener); window.addEventListener('admin-session-expired',expired); return()=>{window.removeEventListener('hashchange',listener);window.removeEventListener('admin-session-expired',expired);}; },[]); useEffect(()=>{ if(auth==='admin'&&route==='dashboard') void getDashboard().then((data)=>setDashboard(data)).catch(()=>setSummary('仪表盘暂时不可用')); },[auth,route]); if(auth==='loading') return <main>正在验证管理员会话…</main>; if(auth==='anonymous') return <main><h1>请先登录</h1><p>管理员后台不接受静态口令。</p><a href="/">返回站点登录</a></main>; if(auth==='denied') return <main><h1>无权访问</h1></main>; const title=nav.find(([key])=>key===route)?.[1]||'仪表盘'; const View=views[route]; return <div className="admin-shell"><aside><strong>Levihan 管理后台</strong><nav>{nav.map(([key,label])=><a key={key} href={`#/${key}`} aria-current={route===key?'page':undefined}>{label}</a>)}</nav></aside><main><h1>{title}</h1>{route==='dashboard'?dashboard?<><p>作品 {dashboard.counts.works} · 待审投稿 {dashboard.counts.pendingSubmissions} · 待审评论 {dashboard.counts.pendingComments} · 举报 {dashboard.counts.pendingReports} · 失败上传 {dashboard.counts.failedUploads}</p><p>数据库 {dashboard.system.databaseVersion} · 快照 {dashboard.system.snapshotVersion??'无'} · COS/存储 {dashboard.system.storageHealth}</p><h2>最近管理员操作</h2><ul>{dashboard.recentAdminActions.map((item,index)=><li key={`${item.createdAt}-${index}`}>{item.action} · {item.createdAt}</li>)}</ul></>:<p>{summary||'加载中…'}</p>:View?<View/>:null}</main></div>; }
