BEGIN;
LOCK TABLE public.admin_console_operations,public.question_bank,public.app_users,public.snapshot_jobs IN SHARE MODE;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM public.admin_console_operations) THEN RAISE EXCEPTION 'rollback_requires_admin_console_export'; END IF; IF EXISTS(SELECT 1 FROM public.question_bank q WHERE q.question_key<>q.id) THEN RAISE EXCEPTION 'rollback_requires_question_version_export'; END IF; END $$;
DROP FUNCTION IF EXISTS public.admin_retry_job_v2(uuid,uuid,uuid,bigint,text,text,text);
DROP FUNCTION IF EXISTS public.admin_set_question_status_v2(uuid,uuid,uuid,integer,text,text,text,text);
DROP FUNCTION IF EXISTS public.admin_update_question_v2(uuid,uuid,uuid,integer,jsonb,text,text,text);
DROP FUNCTION IF EXISTS public.admin_create_question_v2(uuid,uuid,text,jsonb,text[],text,integer,text,text,text);
DROP FUNCTION IF EXISTS public.admin_set_user_status_v2(uuid,uuid,uuid,bigint,text,text,text,text,text);
DROP FUNCTION IF EXISTS public.admin_list_audit_v2(uuid,uuid,text,text,text,integer,timestamptz,uuid);
DROP FUNCTION IF EXISTS public.admin_list_jobs_v2(uuid,uuid,text,text,text,integer,timestamptz,uuid);
DROP FUNCTION IF EXISTS public.admin_list_reports_v2(uuid,uuid,text,text,text,integer,timestamptz,uuid);
DROP FUNCTION IF EXISTS public.admin_list_comments_v2(uuid,uuid,text,text,text,integer,timestamptz,uuid);
DROP FUNCTION IF EXISTS public.admin_list_questions_v2(uuid,uuid,text,text,text,integer,timestamptz,uuid);
DROP FUNCTION IF EXISTS public.admin_list_users_v2(uuid,uuid,text,text,text,integer,timestamptz,uuid);
DROP FUNCTION IF EXISTS public.admin_dashboard_v2(uuid,uuid);
DROP FUNCTION IF EXISTS public.admin_console_replay(uuid,text,text,text);
DROP TABLE public.admin_console_operations;
DROP TRIGGER IF EXISTS upload_files_cleanup_admin_version ON public.upload_files;
DROP FUNCTION IF EXISTS public.bump_upload_cleanup_admin_version();
ALTER TABLE public.upload_files DROP COLUMN cleanup_admin_version;
DROP INDEX IF EXISTS public.question_bank_key_version_key;
ALTER TABLE public.question_bank DROP COLUMN question_key;
ALTER TABLE public.snapshot_jobs DROP COLUMN admin_version;
ALTER TABLE public.app_users DROP COLUMN version;
COMMIT;
