// Generated by scripts/generate-ui-sprite.py. Do not edit by hand.
export const UI_SPRITE_SIZE = { width: 1024, height: 1502 } as const;
export const UI_SPRITES = {
  'game-watermelon': { x: 4, y: 4, width: 199, height: 337 },
  'hange-peek': { x: 207, y: 4, width: 266, height: 330 },
  'restaurant': { x: 477, y: 4, width: 329, height: 321 },
  'levi-peek': { x: 4, y: 345, width: 268, height: 320 },
  'game-hange': { x: 276, y: 345, width: 394, height: 304 },
  'tatakaru': { x: 674, y: 345, width: 341, height: 296 },
  'game-lihan': { x: 4, y: 669, width: 321, height: 285 },
  'volume': { x: 329, y: 669, width: 210, height: 236 },
  'button-wide': { x: 4, y: 958, width: 648, height: 233 },
  'back-to-top': { x: 656, y: 958, width: 126, height: 226 },
  'button-narrow': { x: 4, y: 1195, width: 409, height: 214 },
  'walk-1': { x: 417, y: 1195, width: 92, height: 170 },
  'walk-2': { x: 513, y: 1195, width: 95, height: 170 },
  'walk-3': { x: 612, y: 1195, width: 92, height: 170 },
  'nav-companion': { x: 708, y: 1195, width: 85, height: 157 },
  'resources': { x: 797, y: 1195, width: 89, height: 95 },
  'doujin': { x: 890, y: 1195, width: 87, height: 92 },
  'dispatch': { x: 4, y: 1413, width: 86, height: 85 },
  'home': { x: 94, y: 1413, width: 68, height: 85 },
} as const;
export type UiSpriteName = keyof typeof UI_SPRITES;
